-- CreateEnum
CREATE TYPE "ProjectFeature" AS ENUM ('BOARD', 'TASKS', 'MEMBERS', 'ACTIVITY', 'SETTINGS', 'SPRINTS', 'BACKLOG', 'MILESTONES', 'CALENDAR', 'FILES', 'TIME_TRACKING', 'REPORTS', 'WIKI', 'CHAT', 'NOTIFICATIONS', 'AUTOMATION', 'GOALS', 'CUSTOM_FIELDS', 'ISSUES', 'RELEASES', 'EPICS');

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "features" JSONB NOT NULL DEFAULT '["BOARD","TASKS"]';
